// src/lib/components/PostList.svelte
<script>
  import Post from '$lib/components/Post.svelte'
  import firebase from '$lib/stores/firebase'
  import { deleteDoc, doc } from '@firebase/firestore'

  export let filteredPosts

  const deletePost = async (postId) => {
    try {
      await deleteDoc(doc($firebase.db, 'posts', postId))
    } catch (error) {
      console.error(error.message)
    }
  }
</script>

<section>
  {#each filteredPosts as post}
    <Post {post} {deletePost} />
  {/each}
</section>

// src/components/PostList.jsx
import Post from './Post'
import { db } from '../app/firebase'
import { deleteDoc, doc } from 'firebase/firestore'

const PostList = ({ filteredPosts }) => {
  const deletePost = async (id) => {
    try {
      await deleteDoc(doc(db, 'posts', id))
    } catch (err) {
      console.error(err.message)
    }
  }

  return (
    <section>
      {filteredPosts.map((post) => (
        <Post key={post?.id} post={post} deletePost={deletePost} />
      ))}
    </section>
  )
}

export default PostList
