// src/lib/components/Post.svelte
<script>
  import { scale } from 'svelte/transition'

  export let post
  export let deletePost
</script>

<article transition:scale>
  <strong>Post ID: {post.id}</strong>
  <h2>{post.title}</h2>
  <p>{post.content}</p>
  <button on:click={() => deletePost(post.id)} class="btn danger"> Delete Post </button>
</article>

// src/components/Post.jsx
import React from 'react'

export default function Posts({ post, deletePost }) {
  return (
    <article>
      <strong>Post ID: {post.id}</strong>
      <h2>{post.title}</h2>
      <p>{post.content}</p>
      <button onClick={() => deletePost(post.id)} className='btn danger'>
        Delete Post
      </button>
    </article>
  )
}
