// src/components/Header.jsx
import { auth } from "../app/firebase";
import { useScreenWidth } from "../app/hooks";
import { useStore } from "../app/store";
import { IoLogInOutline, IoLogOutOutline } from "react-icons/io5";
import { signInWithRedirect, GoogleAuthProvider, signOut } from "firebase/auth";

const Header = () => {
  const screenWidth = useScreenWidth();
  const { user } = useStore();

  return (
    <header>
      <h1>🐉 My Posts List</h1>

      {!user ? (
        <button
          className="btn secondary"
          onClick={() => signInWithRedirect(auth, new GoogleAuthProvider())}
        >
          {screenWidth < 548 ? (
            <IoLogInOutline aria-label="Sign In With Google" />
          ) : (
            "Sign In With Google"
          )}
        </button>
      ) : (
        <div className="user-bar">
          <figure className="user-info">
            {screenWidth > 548 && (
              <>
                <figcaption>{user?.username}</figcaption>
                <img src={user?.avatar} alt={`Profile of ${user?.username}`} />
              </>
            )}
          </figure>
          <button className="btn danger" onClick={() => signOut(auth)}>
            {screenWidth < 548 ? (
              <IoLogOutOutline aria-label="Sign Out" />
            ) : (
              "Sign Out"
            )}
          </button>
        </div>
      )}
    </header>
  );
};

export default Header;

// src/lib/components/Header.svelte
<script>
  import { auth, firebase, breakpoint } from '$lib/stores'
  import Login from 'carbon-icons-svelte/lib/Login16'
  import Logout from 'carbon-icons-svelte/lib/Logout16'
  import { signInWithRedirect, GoogleAuthProvider, signOut } from '@firebase/auth'
</script>

<header>
  <h1>🐉 My Posts List</h1>

  {#if !$auth.user}
    <button
      class="btn secondary"
      on:click={() => signInWithRedirect($firebase.auth, new GoogleAuthProvider())}
    >
      {#if $breakpoint < 548}
        <Login aria-label="Sign In With Google" />
      {:else}
        Sign In With Google
      {/if}
    </button>
  {:else}
    <div class="user-bar">
      <figure class="user-info">
        {#if $breakpoint > 548}
          <figcaption>{$auth.user.username}</figcaption>
          <img src={$auth.user.avatar} alt={`Profile of ${$auth.user.username}`} />
        {/if}
      </figure>
      <button class="btn danger" on:click={() => signOut($firebase.auth)}>
        {#if $breakpoint < 548}
          <Logout aria-label="Sign Out" />
        {:else}
          Sign Out
        {/if}
      </button>
    </div>
  {/if}
</header>
